/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 FlyingDisplay.glb --transform
Author: Bogdan Kuznetsov (https://sketchfab.com/kuznetsov_bogdan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-display-3-56c1f433f94c4397abea107b7694d970
Title: Sci-Fi Display (3)
*/

import React, { useRef, memo } from 'react'
import { useGLTF, } from '@react-three/drei'

export function FlyingDisplay(props) {
  const { nodes, materials } = useGLTF('/model/FlyingDisplay/FlyingDisplay-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.0061} position={[0.753, 0.1, 0]}>
        <mesh geometry={nodes.Body_Basic_0.geometry} material={materials.Basic} position={[37.92, -22.57, -0.23]} rotation={[-Math.PI / 2, 0, 0]} scale={106.73} castShadow receiveShadow />
        <mesh geometry={nodes.Big_Display_Big_display_0.geometry} material={materials.Big_display} position={[37.92, -22.57, -0.23]} rotation={[-Math.PI / 2, 0, 0]} scale={106.73} />
        <mesh geometry={nodes.Small_Display_Small_Display_0.geometry} material={materials.Small_Display} position={[37.92, -22.57, -0.23]} rotation={[-Math.PI / 2, 0, 0]} scale={106.73} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/FlyingDisplay/FlyingDisplay-transformed.glb');

