/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Logo3d.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function OneRepublic(props) {
  const { nodes, materials } = useGLTF('/model/OneRepublic/Logo3d-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.22, -0.325, -0.02]} rotation={[1.5, 0, 0]} scale={0.89}>
        <mesh geometry={nodes.Curve.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Curve_1.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/OneRepublic/Logo3d-transformed.glb')
