/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 MultyDisplay.glb --transform
Author: Bogdan Kuznetsov (https://sketchfab.com/kuznetsov_bogdan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-command-panel-0c13e6af91b04f9dbdf13bc646504e15
Title: Sci-Fi Command Panel
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MultyDisplay(props) {
  const { nodes, materials } = useGLTF('/model/MultyDisplay/MultyDisplay-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.0038} position={[-1.42, -0.77, -3.2]} rotation={[0, -0.35, 0]}>
        <mesh geometry={nodes.Cube002_low_Displays_0.geometry} material={materials.Displays} position={[20.04, 105.26, 3.27]} rotation={[-Math.PI / 2, 0, 0]} scale={177.86} />
        <mesh geometry={nodes.Plane_low_Displays_0.geometry} material={materials.Displays} position={[43.06, 298.03, 150.69]} rotation={[0, Math.PI / 2, 0]} scale={168.55} />
        <mesh geometry={nodes.Display_mid_center_Displays_0.geometry} material={materials.Displays} position={[7.4, 298.03, 2.38]} rotation={[0, Math.PI / 2, 0]} scale={168.55} />
        <mesh geometry={nodes.Plane001_low_Displays_0.geometry} material={materials.Displays} position={[20.3, 200.99, 92.1]} rotation={[0, Math.PI / 2, 0]} scale={179.97} />
        <mesh geometry={nodes.Plane004_low_Displays_0.geometry} material={materials.Displays} position={[19.19, 242.5, 92.07]} rotation={[0, Math.PI / 2, 0]} scale={[179.97, 144.02, 179.97]} />
        <mesh geometry={nodes.Plane005_low_Displays_0.geometry} material={materials.Displays} position={[20.51, 160.29, 92.31]} rotation={[0, Math.PI / 2, 0]} scale={179.97} />
        <mesh geometry={nodes.Mesh105005_low_Displays_0.geometry} material={materials.Displays} position={[43.5, 106.68, 136.89]} rotation={[0, -0.01, 0]} scale={204.01} />
        <mesh geometry={nodes.Mesh105006_low_Displays_0.geometry} material={materials.Displays} position={[45.06, 104.89, -125]} rotation={[Math.PI, -0.02, 0]} scale={199.45} />
        <mesh geometry={nodes.Display_high_left_Display_high_left_1_0.geometry} material={materials.Display_high_left_1} position={[22.73, 200.99, 91.51]} rotation={[0, Math.PI / 2, 0]} scale={179.97} />
        <mesh geometry={nodes.Display_high_right_Display_high_right_2_0.geometry} material={materials.Display_high_left_1} position={[22.73, 200.99, -81.42]} rotation={[0, Math.PI / 2, 0]} scale={179.97} />
        <mesh geometry={nodes.Display_Mid_left_Display_Mid_left_0.geometry} material={materials.Display_high_left_1} position={[43.06, 298.03, 150.69]} rotation={[0, Math.PI / 2, 0]} scale={168.55} />
        <mesh geometry={nodes.Display_mid_right_Display_Mid_right_0.geometry} material={materials.Display_high_left_1} position={[43.06, 298.03, 150.69]} rotation={[0, Math.PI / 2, 0]} scale={168.55} />
        <mesh geometry={nodes.Plane_low003_Displays_0.geometry} material={materials.Displays} position={[43.06, 298.03, 150.69]} rotation={[0, Math.PI / 2, 0]} scale={168.55} />
        <mesh geometry={nodes.Display_down_left_Display_down_left_0.geometry} material={materials.Display_high_left_1} position={[43.48, 106.68, 136.91]} rotation={[0, -0.01, 0]} scale={204.01} />
        <mesh geometry={nodes.Display_down_right_Display_down_right_0.geometry} material={materials.Display_high_left_1} position={[45.04, 104.89, -125.02]} rotation={[Math.PI, -0.02, 0]} scale={199.45} />
        <mesh geometry={nodes.Display_down_centre_Display_down_centre_0.geometry} material={materials.Display_high_left_1} position={[20.04, 105.26, 3.27]} rotation={[-Math.PI / 2, 0, 0]} scale={177.86} />
        <mesh geometry={nodes.Display_mid_center001_Display_mid_center_0.geometry} material={materials.Display_high_left_1} position={[7.4, 298.03, 2.38]} rotation={[0, Math.PI / 2, 0]} scale={168.55} />
        <mesh geometry={nodes.Plane001_low002_Displays_0.geometry} material={materials.Displays} position={[20.3, 200.99, 109.93]} rotation={[0, Math.PI / 2, 0]} scale={179.97} />
        <mesh geometry={nodes.Plane004_low001_Displays_0.geometry} material={materials.Displays} position={[19.19, 242.5, 109.9]} rotation={[0, Math.PI / 2, 0]} scale={[179.97, 144.02, 179.97]} />
        <mesh geometry={nodes.Plane005_low001_Displays_0.geometry} material={materials.Displays} position={[20.51, 160.29, 110.14]} rotation={[0, Math.PI / 2, 0]} scale={179.97} />
        <mesh geometry={nodes.Plane001_low003_Displays_0.geometry} material={materials.Displays} position={[19.11, 401.73, 92.5]} rotation={[0, Math.PI / 2, 0]} scale={182.95} />
        <mesh geometry={nodes.Plane004_low002_Displays_0.geometry} material={materials.Displays} position={[17.99, 443.93, 92.47]} rotation={[0, Math.PI / 2, 0]} scale={[182.95, 146.41, 182.95]} />
        <mesh geometry={nodes.Plane005_low002_Displays_0.geometry} material={materials.Displays} position={[19.33, 360.35, 92.71]} rotation={[0, Math.PI / 2, 0]} scale={182.95} />
        <mesh geometry={nodes.Display_high_left001_Display_high_left_0.geometry} material={materials.Display_high_left_1} position={[21.58, 401.73, 91.9]} rotation={[0, Math.PI / 2, 0]} scale={182.95} />
        <mesh geometry={nodes.Display_high_right001_Display_high_right_0.geometry} material={materials.Display_high_left_1} position={[21.58, 401.73, -83.9]} rotation={[0, Math.PI / 2, 0]} scale={182.95} />
        <mesh geometry={nodes.Plane001_low004_Displays_0.geometry} material={materials.Displays} position={[19.11, 401.73, 110.62]} rotation={[0, Math.PI / 2, 0]} scale={182.95} />
        <mesh geometry={nodes.Plane004_low003_Displays_0.geometry} material={materials.Displays} position={[17.99, 443.93, 110.6]} rotation={[0, Math.PI / 2, 0]} scale={[182.95, 146.41, 182.95]} />
        <mesh geometry={nodes.Plane005_low003_Displays_0.geometry} material={materials.Displays} position={[19.33, 360.35, 110.84]} rotation={[0, Math.PI / 2, 0]} scale={182.95} />
        <mesh geometry={nodes.Side_panel_low_Panels_0.geometry} material={materials.Panels} position={[62.98, 26.07, 147.16]} scale={184.82} />
        <mesh geometry={nodes.Central_low_Panels_0.geometry} material={materials.Panels} position={[63.29, 53.54, 7.38]} rotation={[0, 0.06, 0]} scale={236.99} />
        <mesh geometry={nodes.Body_low_Panels_0.geometry} material={materials.Panels} position={[46.48, 19.67, 9.29]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
        <mesh geometry={nodes.Bottom_low_Panels_0.geometry} material={materials.Panels} position={[46.48, 18.48, 9.29]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
        <mesh geometry={nodes.Side_panel_low001_Panels_0.geometry} material={materials.Panels} position={[64.2, 26.07, -133.68]} rotation={[-Math.PI / 2, 0, 0]} scale={184.82} />
        <mesh geometry={nodes.Side_panel_low002_Panels_0.geometry} material={materials.Panels} position={[58.73, 31.49, -127.47]} rotation={[-Math.PI / 2, 0, 0]} scale={152.58} />
        <mesh geometry={nodes.Side_panel_low003_Panels_0.geometry} material={materials.Panels} position={[58.73, 25.41, -127.47]} rotation={[-Math.PI / 2, 0, 0]} scale={152.58} />
        <mesh geometry={nodes.Side_panel_low004_Panels_0.geometry} material={materials.Panels} position={[56.06, 31.49, 141.78]} scale={152.58} />
        <mesh geometry={nodes.Side_panel_low005_Panels_0.geometry} material={materials.Panels} position={[56.06, 25.71, 141.78]} scale={152.58} />
        <mesh geometry={nodes.Side_panel_low006_Panels_0.geometry} material={materials.Panels} position={[56.06, 28.11, 141.78]} scale={152.58} />
        <mesh geometry={nodes.Side_panel_low007_Panels_0.geometry} material={materials.Panels} position={[58.73, 28.02, -127.47]} rotation={[-Math.PI / 2, 0, 0]} scale={152.58} />
        <mesh geometry={nodes.Part_1002_Body_0.geometry} material={materials.Body} position={[85.49, 318.44, 4.77]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={189.84} />
        <mesh geometry={nodes.Part_1001_Body_0.geometry} material={materials.Body} position={[83.03, 224.32, 2.14]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={174.98} />
        <mesh geometry={nodes.Part_1004_Body_0.geometry} material={materials.Body} position={[92.46, 419.55, 10.02]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={204.75} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/MultyDisplay/MultyDisplay-transformed.glb')
