/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 NES.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NES(props) {
  const { nodes, materials } = useGLTF('/model/NES/NES-transformed.glb')
  return (
    <group {...props} dispose={null} rotation={[1.5, 0, 0]} scale={0.27} position={[-0.16, -0.11, 0]}>
      <mesh geometry={nodes.Plane030.geometry} material={materials['Material.033']} />
      <mesh geometry={nodes.Plane030_1.geometry} material={materials['Material.032']} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.034']} />
      <mesh geometry={nodes.Plane009.geometry} material={materials['Material.035']} />
      <mesh geometry={nodes.Plane010.geometry} material={materials['Material.035']} />
    </group>
  )
}

useGLTF.preload('/model/NES/NES-transformed.glb')
