/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 pedestal.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pedestal(props) {
  const { nodes, materials } = useGLTF('/model/Pedestal/pedestal-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.71, 0]} rotation={[0, 2.1, 0]} scale={0.14}>
        <mesh geometry={nodes.Меш006.geometry} material={materials.Plastic1} castShadow receiveShadow />
        <mesh geometry={nodes.Меш006_1.geometry} material={materials.Metal} castShadow receiveShadow />
        <mesh geometry={nodes.Меш006_2.geometry} material={materials.Ligh} receiveShadow />
      </group>
    </group>
  )
}

useGLTF.preload('/model/Pedestal/pedestal-transformed.glb')
