/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 player.gltf --transform
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Player(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/model/Player/player-transformed.glb');
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature_druide" scale={0.5} position={[0, -0.28, 0]}>
          <primitive object={nodes.root} />
          <skinnedMesh name="druid" geometry={nodes.druid.geometry} material={materials.color_main} skeleton={nodes.druid.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/Player/player-transformed.glb')
