/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 player.gltf --transform
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Player(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/model/Player/player-transformed.glb');
  const { actions } = useAnimations(animations, group);

  return (
    <group name="Armature_druide" >
      <primitive object={nodes.root} scale={0.5} position={[0, -0.30, 0]} />
      <skinnedMesh name="druid" geometry={nodes.druid.geometry} material={materials.color_main} skeleton={nodes.druid.skeleton} />
    </group>
  )
}

useGLTF.preload('/model/Player/player-transformed.glb')
