/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 window.glb --transform
Author: Bogdan Kuznetsov (https://sketchfab.com/kzn.bog)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-display-27941cd9eba845f180a521839b479f15
Title: Sci-fi Display
*/


import { useGLTF, useVideoTexture, } from '@react-three/drei'

export function Window(props) {
  const { nodes, materials } = useGLTF('/model/Window/window-transformed.glb')
  const video = useVideoTexture('/Video/CityBackground.webm')

  return (
    <group dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[0.63, -0, -3.2]} scale={0.6} >
        <mesh geometry={nodes.Object_2.geometry} material={materials.Basic} />
        <mesh geometry={nodes.Object_3.geometry}>
          <meshStandardMaterial map={video} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/model/Window/window-transformed.glb')
